### ISSUE TITLE
Stage start API 수정

### ISSUE THREAD

**Issue by HanCiHu** [I-Need-Mac/ShadowOfMoon-Server#26]
- stage 시작 할때 key 값도 같이 요청에 보내주도록 수정
- 해당 key값 만큼 asset 테이블에서 값 소모되게 수정
- 만약 소모될 key 값이 없는 경우 에러 발생

**Comment by sang4004** [comment]
![start](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/673e46ee-0daf-499f-88b0-732976346edd)
/start api 수정 완료
