### ISSUE TITLE
Stage End API 구현

### ISSUE THREAD

**Issue by HanCiHu** [I-Need-Mac/ShadowOfMoon-Server#27]
- 스테이지가 끝난 후 API 구현
- 클라이언트에서 다음과 같은 데이터를 body로 보내줌
``` 
{
  user_id: uuid
  stage_id: int
  reward_box: [801, 801, 802, 803]
  is_clear: bool
  play_time: int (ms)
}
```
- 응답은 다음과 같음.
```
{
  user_id: uuid
  stage: int
  reward_box: [int 배열]
  key: int (개수)
  updated_at: timestamp (datetime)
}
```
- Stage 테이블 업데이트, reward_box 테이블 업데이트가 되어야하지만 이번 이슈에서는 Stage 테이블 업데이트 로직만 구현한다.
- reward_box 테이블 업데이트는 해당 부분의 데이터가 구현이 되면 그때 추가 구현 !

**Comment by sang4004** [comment]
![end](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/be2b4f05-6ca1-49f6-b001-0123abc830b8)
/end api 구현 완료 /start 수정 작업 올리며 같이 /end api가 올라가버림
