### ISSUE TITLE
stage 관련 API 오류 해결하기

### ISSUE THREAD

**Issue by HanCiHu** [I-Need-Mac/ShadowOfMoon-Server#35]
1. stage start API 에서 presets update로직으로 바꿔주기
2. stage end API 에서 stage id를 통해 업데이트 해주도록 변경

**Comment by sang4004** [comment]
수정 완료 후 커밋 완료 
![1](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/f562feb1-65af-41bf-850d-e6ecf2108b16)
![2](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/0307704e-cf35-43ac-ba4f-a6a252996757)
