### ISSUE TITLE
Preset 정보 가져오는 API

### ISSUE THREAD

**Issue by HanCiHu** [I-Need-Mac/ShadowOfMoon-Server#36]
1. GET ::/preset/soul
2. GET ::/preset/character

preset 정보를 가져오는 API
GET 요청이기때문에 body 필요없음
암호화 로직이 필요없으므로 middleware에서 exception을 걸어주는 로직이 필요할 것 같음.

user module exclude 부분 참고 !
```
export class UsersModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(DecryptionMiddleware)
      .exclude(
        {
          path: 'auth/duplicated',
          method: RequestMethod.GET,
        },
        {
          path: 'auth/users',
          method: RequestMethod.GET,
        },
      )
      .forRoutes('auth');
  }
}

```

**Comment by sang4004** [comment]
preset/soul, preset/character Api 추가 완료

![2](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/95d9722e-bbb2-4701-a85b-3f4a35832cd5)
![1](https://github.com/I-Need-Mac/ShadowOfMoon-Server/assets/74955871/f6f6703e-bd52-439b-9ef4-5b68cfc600e3)
